In [2]:
import numpy as np 

In [3]:
# # Non-vectorized approach (slow)
def add_arrays_loop(a, b):
    print('add_arrays_loop()\n')
    result = np.empty_like(a)
    for i in range(len(a)):
        result[i] = a[i] + b[i]
        print(f'a[i] + b[i] = {a[i]} + {b[i]} = {result[i]}')
    return result

# Vectorized approach (fast)
def add_arrays_vectorized(a, b):
    print('\n\nadd_arrays_vectorized function()\n')
    print(f'a + b = {a} + {b} = {a + b}')
    return a + b

# Usage
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

result_non_vectorized = add_arrays_loop(a, b)
result_vectorized = add_arrays_vectorized(a, b)

add_arrays_loop()

a[i] + b[i] = 1 + 5 = 6
a[i] + b[i] = 2 + 6 = 8
a[i] + b[i] = 3 + 7 = 10
a[i] + b[i] = 4 + 8 = 12


add_arrays_vectorized function()

a + b = [1 2 3 4] + [5 6 7 8] = [ 6  8 10 12]


<h2>Broadcasting in NumPy</h2>
<p>a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations. It automatically expands smaller arrays to match the shape of larger arrays without making copies of the data. This enables efficient operations between arrays of different sizes.</p>

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([10])
c = a + b  # b is broadcast to match a's shape
# c becomes [11, 12, 13, 14]
print(f'a + b = {a} + {b} = {c}')

a + b = [1 2 3 4] + [10] = [11 12 13 14]


<h2>ufun - universal functions</h2>
<p>A ufunc is a function that operates element-wise on array inputs. These functions are vectorized and optimized for performance. NumPy provides many built-in ufuncs, and you can also create custom ones.</p>

<h2>Follow along</h2>
<p>We will follow along now with the ZTM's introduction to AI course. Everything above was based on a conversation I had with Claude AI.</p>

## Notes

- **Main datatype:** The main datatype is ndarray
- **ndarray (n-dimensional array):** n-dimensions indicate it can be any shape you can imagine and array's can be a list of numbers too.
- **numpy.shape** can be shown as it is here

![anatomy of a numpy array](anatomy-of-a-numpy-array.png)

- **ndim:** stands for number of dimensions
- **numpy.shape**
  - 1 - dimension: (x,)
  - 2 - dimension: (x,y)
  - 3 - dimension: (x,y,z)
  - It can go to n-dimensions depending on what kind of data you're working with
- The number of dimensions are important to know b/c perhaps a machine-learning algorithm will find a pattern in the number of dimensions
- Creating arrays.
    - Type *variable = np.array([1, 2, 3])* or however you might populate a list within the parameter
    - **variable = np.ones()** returns an array of ones
    - **variable = np.zeros()** returns an array of 0's.
    - **variable = np.arange(start, ends, step)** gives a range of values with a start and end. The step is how often the value will step for example .arange(0, 10, 2) would result in the following array [0, 2, 4, 6, 8]. 
    - **variable = np.random.random((x,y))** returns an array with random numbers having x rows and y columns.
    - **random_array3** = np.random.randint(10, size=(5, 3))  # make vaulues 0 to 10
    - You can plant the **seed** before creating random numbers; the seed is used to initialize the random number generator. Setting a specific seed ensures that the sequence of "random" numbers generated after that will always be the same.
 

In [5]:
# ndarray demo
a1 = np.array([1, 2, 3])  # pass a list of numbers
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([
                [1, 2.0, 3.3], 
                [4, 5, 6.5]
            ])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [10]:
 a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(3, 2, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
# a2 will convert the rest of the int's into floats
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [15]:
# Determine size
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# Create a DataFrame from NumPy Array 
import pandas as pd 

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## **2. Creating Arrays**

In [18]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int32')

In [20]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [25]:
# Challenge, change the data type within ones 
ones = ones.astype(np.int64)
ones

array([[1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [27]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [29]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[2, 5, 5, 5, 7],
       [2, 1, 2, 3, 3],
       [5, 1, 6, 1, 4]])

In [36]:
random_array2 = np.random.random((5,3))
print(random_array2)
print(f'Shape: {random_array2.shape}')

[[0.53545134 0.92948606 0.61034678]
 [0.67685308 0.12079174 0.31359707]
 [0.89112704 0.4431681  0.45642868]
 [0.76814193 0.30122092 0.77969718]
 [0.19227131 0.08448178 0.30420188]]
Shape: (5, 3)


In [43]:
# Pseudo-random numbers 
np.random.seed(seed=7)  # generates random numbers that are reproducable 
random_array3 = np.random.randint(10, size=(5, 3))  # make vaulues 0 to 10
random_array3

array([[4, 9, 6],
       [3, 3, 7],
       [7, 9, 7],
       [8, 9, 8],
       [7, 6, 4]])

In [44]:
random_array4 = np.random.random((5,3))
random_array4

array([[0.86880146, 0.33083925, 0.39294231],
       [0.67433042, 0.67231727, 0.69403158],
       [0.34597294, 0.92952819, 0.26258377],
       [0.75076273, 0.25489406, 0.85129459],
       [0.17405276, 0.79076351, 0.93762934]])