# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [7]:
# Create a 1-dimensional NumPy array using np.array()
m_array1 = np.array([1, 2, 3])
print(f'm_array1 = {m_array1}\n')

# Create a 2-dimensional NumPy array using np.array()
m_array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(f'm_array2 = \n{m_array2}\n')


# Create a 3-dimensional Numpy array using np.array()
m_array3 = np.array([[[1, 2, 3],
                      [4, 5, 6],
               [7, 8, 9]],
                [[10, 11, 12],
               [13, 14, 15],
                [16, 17, 18]]])
print(f'm_array3 = \n{m_array3}')

m_array1 = [1 2 3]

m_array2 = 
[[1 2 3]
 [4 5 6]]

m_array3 = 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [10]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print('1-dimensional array attributes\n')
print(f'm_array1 shape = {m_array1.shape}')
print(f'm_array1 data type = {m_array1.dtype}')
print(f'm_array1 size = {m_array1.size}')
print(f'm_array1 type = {type(m_array1)}')

1-dimensional array attributes

m_array1 shape = (3,)
m_array1 data type = int32
m_array1 size = 3
m_array1 type = <class 'numpy.ndarray'>


In [12]:
# Attributes of 2-dimensional array
print('2-dimensional array attributes\n')
print(f'm_array2 shape = {m_array2.shape}')
print(f'm_array2 data type = {m_array2.dtype}')
print(f'm_array2 size = {m_array2.size}')
print(f'm_array2 type = {type(m_array2)}')

2-dimensional array attributes

m_array2 shape = (2, 3)
m_array2 data type = int32
m_array2 size = 6
m_array2 type = <class 'numpy.ndarray'>


In [13]:
# Attributes of 3-dimensional array

print('3-dimensional array attributes\n')
print(f'm_array3 shape = {m_array3.shape}')
print(f'm_array3 data type = {m_array3.dtype}')
print(f'm_array3 size = {m_array3.size}')
print(f'm_array3 type = {type(m_array3)}')

3-dimensional array attributes

m_array3 shape = (2, 3, 3)
m_array3 data type = int32
m_array3 size = 18
m_array3 type = <class 'numpy.ndarray'>


In [14]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(m_array1)

In [17]:
# Create an array of shape (10, 2) with only ones
m_ones = np.ones((10, 2))
print(f'm_ones = {m_ones}')

m_ones = [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
# Create an array of shape (7, 2, 3) of only zeros
m_zeros = np.zeros((7, 2, 3))
print(f'm_zeros = \n{m_zeros}')

m_zeros = 
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [19]:
# Create an array within a range of 0 and 100 with step 3
m_range_array = np.arange(0, 100, 3)
print(f'm_range_array = \n{m_range_array}')

m_range_array = 
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [23]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
m_random_arr = np.random.randint(10, size=(7,2))
print(f'm_random_arr = \n{m_random_arr}')

m_random_arr = 
[[9 7]
 [0 0]
 [0 8]
 [6 7]
 [6 4]
 [2 5]
 [1 4]]


In [25]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
m_random_arr_float = np.random.random((3, 5))
print(f'm_random_arr_float = \n{m_random_arr_float}')

m_random_arr_float = 
[[0.53305865 0.1456     0.30284378 0.64216834 0.06598727]
 [0.53432009 0.08444395 0.85731922 0.25694159 0.33470625]
 [0.94548327 0.15448115 0.66042997 0.66562182 0.3817532 ]]


In [31]:
# Set the random seed to 42
np.random.seed(seed=42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
m_random_arr2 = np.random.randint(10, size=(4,6))
print(f'm_random_arr2 = \n{m_random_arr2}')

m_random_arr2 = 
[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [29]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
m_random_arr3 = np.random.randint(11, size=(3,7))

# Find the unique numbers in the array you just created
print(f'm_random_arr3 = \n{m_random_arr3}')
print(f'm_random_arr3 unique = \n{np.unique(m_random_arr2)}')

m_random_arr3 = 
[[4 1 3 6 7 2 0]
 [3 1 7 3 1 5 5]
 [9 3 5 1 9 1 9]]
m_random_arr3 unique = 
[0 1 2 3 4 5 6 7 9]


In [33]:
# Find the 0'th index of the latest array you created
m_random_arr3[0]

array([4, 1, 3, 6, 7, 2, 0])

In [34]:
# Get the first 2 rows of latest array you created
m_random_arr3[:2]

array([[4, 1, 3, 6, 7, 2, 0],
       [3, 1, 7, 3, 1, 5, 5]])

In [37]:
# Get the first 2 values of the first 2 rows of the latest array
print(f'm_random_arr3 = \n{m_random_arr3}')
print(f'first 2 valuse of the first 2 rows = \n{m_random_arr3[:2, :2]}')

m_random_arr3 = 
[[4 1 3 6 7 2 0]
 [3 1 7 3 1 5 5]
 [9 3 5 1 9 1 9]]
first 2 valuse of the first 2 rows = 
[[4 1]
 [3 1]]


In [39]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
m_random_arr4 = np.random.randint(10, size=(3,5))
m_ones_v2 = np.ones((3,5))
print(f'm_random_arr4 = \n{m_random_arr4}')
print(f'm_ones_v2 = \n{m_ones_v2}')

m_random_arr4 = 
[[0 9 2 6 3]
 [8 2 4 2 6]
 [4 8 6 1 3]]
m_ones_v2 = 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:
# Add the two arrays together
m_random_arr4 + m_ones_v2 

array([[ 1., 10.,  3.,  7.,  4.],
       [ 9.,  3.,  5.,  3.,  7.],
       [ 5.,  9.,  7.,  2.,  4.]])

In [42]:
# Create another array of ones of shape (5, 3)
m_ones_v3 = np.ones((5,3))
m_ones_v3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
# Try add the array of ones and the other most recent array together
m_ones_v3 + m_ones_v2

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [44]:
# Create another array of ones of shape (3, 5)
m_ones_v4 = np.ones((3,5))

In [51]:
# Subtract the new array of ones from the other most recent array
m_random_arr4 - m_ones_v4

array([[-1.,  8.,  1.,  5.,  2.],
       [ 7.,  1.,  3.,  1.,  5.],
       [ 3.,  7.,  5.,  0.,  2.]])

In [52]:
# Multiply the ones array with the latest array
m_random_arr4 * m_ones_v4

array([[0., 9., 2., 6., 3.],
       [8., 2., 4., 2., 6.],
       [4., 8., 6., 1., 3.]])

In [53]:
# Take the latest array to the power of 2 using '**'
m_random_arr4 ** 2

array([[ 0, 81,  4, 36,  9],
       [64,  4, 16,  4, 36],
       [16, 64, 36,  1,  9]])

In [54]:
# Do the same thing with np.square()
np.square(m_random_arr4)

array([[ 0, 81,  4, 36,  9],
       [64,  4, 16,  4, 36],
       [16, 64, 36,  1,  9]])

In [58]:
# Find the mean of the latest array using np.mean()
print(f'np.mean(m_random_arr4) = {np.mean(m_random_arr4):,.2}')

np.mean(m_random_arr4) = 4.3


In [60]:
# Find the maximum of the latest array using np.max()
print(f'np.max(m_random_arr4) = {np.max(m_random_arr4):,}')

np.max(m_random_arr4) = 9


In [61]:
# Find the minimum of the latest array using np.min()
print(f'np.min(m_random_arr4) = {np.min(m_random_arr4)}')

np.min(m_random_arr4) = 0


In [63]:
# Find the standard deviation of the latest array
print(f'np.std(m_random_arr4) = {np.std(m_random_arr4):,.2}')

np.std(m_random_arr4) = 2.7


In [65]:
# Find the variance of the latest array
print(f'np.var(m_random_arr4) = {np.var(m_random_arr4):,.2}')

np.var(m_random_arr4) = 7.1


In [67]:
# Reshape the latest array to (3, 5, 1)
m_random_arr4_modified = m_random_arr4.reshape(3, 5, 1)
m_random_arr4_modified

array([[[0],
        [9],
        [2],
        [6],
        [3]],

       [[8],
        [2],
        [4],
        [2],
        [6]],

       [[4],
        [8],
        [6],
        [1],
        [3]]])

In [68]:
# Transpose the latest array
m_random_arr4_modified.T

array([[[0, 8, 4],
        [9, 2, 8],
        [2, 4, 6],
        [6, 2, 1],
        [3, 6, 3]]])

What does the transpose do?

**A:** The transpose operation, denoted by .T in NumPy, effectively flips the axes of an array. It's a way of restructuring the array so that rows become columns and vice versa. Let's break down what happened in your specific case:

Original shape:
1. Your m_random_arr4_modified had a shape of (3, 5, 1)
 - 3 "layers"
 - Each layer had 5 rows
 - Each row had 1 column
2. After transpose: The resulting shape is (1, 5, 3)
- Now there's 1 "layer"
- It has 5 rows
- Each row has 3 columns

In [73]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
m_random_arr5 = np.random.randint(10, size=(3,2))
m_random_arr6 = np.random.randint(10, size=(3,3))
print(f'm_random_arr5 = \n{m_random_arr5}')
print(f'm_random_arr6 = \n{m_random_arr6}')

m_random_arr5 = 
[[1 0]
 [6 6]
 [7 4]]
m_random_arr6 = 
[[2 7 5]
 [2 0 2]
 [4 2 0]]


In [77]:
# Perform a dot product on the two newest arrays you created
print(f'm_random_arr6.dot(m_random_arr6)  = \n{m_random_arr6.dot(m_random_arr5)}')

m_random_arr6.dot(m_random_arr6)  = 
[[79 62]
 [16  8]
 [16 12]]


In [79]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
m_random_arr7 = np.random.randint(10, size=(4,3))
m_random_arr8 = np.random.randint(10, size=(4,3))
print(f'm_random_arr7 = \n{m_random_arr7}')
print(f'm_random_arr8 = \n{m_random_arr8}')

m_random_arr7 = 
[[3 9 6]
 [8 6 0]
 [0 8 8]
 [3 8 2]]
m_random_arr8 = 
[[6 5 7]
 [8 4 0]
 [2 9 7]
 [5 7 8]]


In [80]:
# Perform a dot product on the two newest arrays you created
print(f'm_random_arr7.dot(m_random_arr8) = \n{m_random_arr7.dot(m_random_arr8)}')

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [81]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
print(f'm_random_arr7.dot(m_random_arr8) = \n{m_random_arr7.dot(m_random_arr8.T)}')

m_random_arr7.dot(m_random_arr8) = 
[[105  60 129 126]
 [ 78  88  70  82]
 [ 96  32 128 120]
 [ 72  56  92  87]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [83]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
m_random_arr9 = np.random.randint(10, size=(3, 3))
m_random_arr10 = np.random.randint(10, size=(3, 3))
print(f'm_random_arr9 = \n{m_random_arr9}')
print(f'm_random_arr10 = \n{m_random_arr9}')

In [39]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [40]:
# Compare the two arrays with '>='


In [41]:
# Find which elements of the first array are greater than 7


In [42]:
# Which parts of each array are equal? (try using '==')


In [43]:
# Sort one of the arrays you just created in ascending order


In [44]:
# Sort the indexes of one of the arrays you just created


In [45]:
# Find the index with the maximum value in one of the arrays you've created


In [46]:
# Find the index with the minimum value in one of the arrays you've created


In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [49]:
# Create an array of normally distributed random numbers


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.